<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class arsip extends Model
{
    use HasFactory;
 
    protected $table = 'arsip';

    protected $fillable = [
        'siswa_id',
        'NOPDF',
        'NamaLengkap',
        'NomorInduk',
        'NamaPanggilan',
        'JenisKelamin',
        'NISN',
        'TempatLahir',
        'TanggalLahir',
        'Agama',
        'Alamat',
        'RT',
        'RW',
        'Kelurahan',
        'Kecamatan',
        'KabKota',
        'Provinsi',
        'KodePos',
        'Email',
        'NomorTelephone',
        'Kewarganegaraan',
        'NIK',
        'GolDarah',
        'TinggalDengan',
        'StatusSiswa',
        'AnakKe',
        'SaudaraKandung',
        'SaudaraTiri',
        'Tinggicm',
        'Beratkg',
        'RiwayatPenyakit',
        'AsalSMP',
        'AlamatSMP',
        'NPSNSMP',
        'KabKotaSMP',
        'ProvinsiSMP',
        'NoIjasah',
        'NoSKHUN',
        'DiterimaTanggal',
        'DiterimaDiKelas',
        'DiterimaSemester',
        'MutasiAsalSMA',
        'AlasanPindah',
        'NoPesertaUNSMP',
        'TglIjasah',
        'NamaOrangTuaPadaIjasah',
        'NamaAyah',
        'TahunLahirAyah',
        'AlamatAyah',
        'NomorTelephoneAyah',
        'AgamaAyah',
        'PendidikanTerakhirAyah',
        'PekerjaanAyah',
        'PenghasilanAyah',
        'NamaIbu',
        'TahunLahirIbu',
        'AlamatIbu',
        'NomorTelephoneIbu',
        'AgamaIbu',
        'PendidikanTerakhirIbu',
        'PekerjaanIbu',
        'PenghasilanIbu',
        'NamaWali',
        'TahunLahirWali',
        'AlamatWali',
        'NomorTelephoneWali',
        'AgamaWali',
        'PendidikanTerakhirWali',
        'PekerjaanWali',
        'WaliPenghasilan',
        'StatusHubunganWali',
        'MenerimaBeasiswaDari',
        'TahunMeninggalkanSekolah',
        'AlasanSebab',
        'TamatBelajarTahun',
        'TanggalNomorSTTB',
        'InformasiLain',
        'cita',
        'no_pdf',
        'angkatan',
    ];
    protected $primaryKey = 'siswa_id';
}